/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { core } from "@nexus/schema"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
}

export interface NexusGenObjects {
  Gorevlendirmeler: { // root type
    aciklama?: string | null; // String
    aktif?: string | null; // String
    ana_gorev_saat?: string | null; // String
    baslik?: string | null; // String
    bitirilmesi_gereken_saat?: string | null; // String
    bitirilmesi_gereken_tarih?: NexusGenScalars['Date'] | null; // Date
    eklenme_saati?: string | null; // String
    eklenme_tarihi?: NexusGenScalars['Date'] | null; // Date
    gorev_numara?: number | null; // Int
    muhlet_bitis_saati?: string | null; // String
    muhlet_bitis_tarihi?: NexusGenScalars['Date'] | null; // Date
    numara?: number | null; // Int
    personel_numara?: number | null; // Int
    saat?: string | null; // String
    surec_numara?: number | null; // Int
    termin_dk?: number | null; // Int
    termin_gun?: number | null; // Int
    termin_saat?: number | null; // Int
  }
  Mutation: {};
  Query: {};
  Yonetim: { // root type
    eposta?: string | null; // String
    kisa_ad?: string | null; // String
    kullanici?: string | null; // String
    numara?: number | null; // Int
    yetkiler?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Gorevlendirmeler: { // field return type
    aciklama: string | null; // String
    aktif: string | null; // String
    ana_gorev_saat: string | null; // String
    baslik: string | null; // String
    bitirilmesi_gereken_saat: string | null; // String
    bitirilmesi_gereken_tarih: NexusGenScalars['Date'] | null; // Date
    eklenme_saati: string | null; // String
    eklenme_tarihi: NexusGenScalars['Date'] | null; // Date
    gorev_numara: number | null; // Int
    gorevlipersonel: NexusGenRootTypes['Yonetim'] | null; // Yonetim
    muhlet_bitis_saati: string | null; // String
    muhlet_bitis_tarihi: NexusGenScalars['Date'] | null; // Date
    numara: number | null; // Int
    personel_numara: number | null; // Int
    saat: string | null; // String
    surec_numara: number | null; // Int
    termin_dk: number | null; // Int
    termin_gun: number | null; // Int
    termin_saat: number | null; // Int
  }
  Mutation: { // field return type
    createDraft: NexusGenRootTypes['Gorevlendirmeler'] | null; // Gorevlendirmeler
    deletePost: NexusGenRootTypes['Gorevlendirmeler'] | null; // Gorevlendirmeler
    publish: NexusGenRootTypes['Gorevlendirmeler'] | null; // Gorevlendirmeler
    signupUser: NexusGenRootTypes['Yonetim'] | null; // Yonetim
  }
  Query: { // field return type
    drafts: Array<NexusGenRootTypes['Gorevlendirmeler'] | null> | null; // [Gorevlendirmeler]
    feed: Array<NexusGenRootTypes['Gorevlendirmeler'] | null> | null; // [Gorevlendirmeler]
    filterPosts: Array<NexusGenRootTypes['Gorevlendirmeler'] | null> | null; // [Gorevlendirmeler]
    gorevlendirme: NexusGenRootTypes['Gorevlendirmeler'] | null; // Gorevlendirmeler
  }
  Yonetim: { // field return type
    eposta: string | null; // String
    gorevleri: Array<NexusGenRootTypes['Gorevlendirmeler'] | null> | null; // [Gorevlendirmeler]
    kisa_ad: string | null; // String
    kullanici: string | null; // String
    numara: number | null; // Int
    yetkiler: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  Gorevlendirmeler: { // field return type name
    aciklama: 'String'
    aktif: 'String'
    ana_gorev_saat: 'String'
    baslik: 'String'
    bitirilmesi_gereken_saat: 'String'
    bitirilmesi_gereken_tarih: 'Date'
    eklenme_saati: 'String'
    eklenme_tarihi: 'Date'
    gorev_numara: 'Int'
    gorevlipersonel: 'Yonetim'
    muhlet_bitis_saati: 'String'
    muhlet_bitis_tarihi: 'Date'
    numara: 'Int'
    personel_numara: 'Int'
    saat: 'String'
    surec_numara: 'Int'
    termin_dk: 'Int'
    termin_gun: 'Int'
    termin_saat: 'Int'
  }
  Mutation: { // field return type name
    createDraft: 'Gorevlendirmeler'
    deletePost: 'Gorevlendirmeler'
    publish: 'Gorevlendirmeler'
    signupUser: 'Yonetim'
  }
  Query: { // field return type name
    drafts: 'Gorevlendirmeler'
    feed: 'Gorevlendirmeler'
    filterPosts: 'Gorevlendirmeler'
    gorevlendirme: 'Gorevlendirmeler'
  }
  Yonetim: { // field return type name
    eposta: 'String'
    gorevleri: 'Gorevlendirmeler'
    kisa_ad: 'String'
    kullanici: 'String'
    numara: 'Int'
    yetkiler: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createDraft: { // args
      aciklama?: string | null; // String
      baslik?: string | null; // String
      eposta?: string | null; // String
    }
    deletePost: { // args
      gorevlendirmeId?: string | null; // String
    }
    publish: { // args
      gorevlendirmeId?: string | null; // String
    }
    signupUser: { // args
      eposta?: string | null; // String
      kisa_ad?: string | null; // String
      kullanici?: string | null; // String
      numara?: number | null; // Int
      yetkiler?: string | null; // String
    }
  }
  Query: {
    filterPosts: { // args
      searchString?: string | null; // String
    }
    gorevlendirme: { // args
      gorevlendirmeId?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}